export enum EKycStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  FlAGGED = "FLAGGED",
}

export enum ECampaignStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  SUSPICIOUS = "SUSPICIOUS",
}

export enum NotificationType {
  DONATION = "DONATION",
  COMMENT = "COMMENT",
  CAMPAIGN_APPROVED = "CAMPAIGN_APPROVED",
  CAMPAIGN_REJECTED = "CAMPAIGN_REJECTED",
  KYC_VERIFIED = "KYC_VERIFIED",
  KYC_REJECTED = "KYC_REJECTED",
  SYSTEM_ALERT = "SYSTEM_ALERT",
}
