export enum EKycStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  FlAGGED = "FLAGGED",
}

export enum ECampaignStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  SUSPICIOUS = "SUSPICIOUS",
}
